import "./globals.css";
import { ThemeProvider } from '@/context/ThemeContext';
import StoreProvider from "./StoreProvider";
export const metadata = {
  title: "Taskflow",
  description: "Generated by mankarshubham81",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <ThemeProvider>
          <StoreProvider>
            {children}
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}


// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <ThemeProvider>
//           {children}
//         </ThemeProvider>
//       </body>
//     </html>
//   )
// }